

class Config:

    title_book_adventure_error = 'Ghbrk.ctybz'
    title_book1 = 'Война и мир'
    title_book2 = 'Уроки французского'
    title_book3 = 'Аудиокниги'
    author = 'Николай Свечин'
    title_book_adventure = 'Приключения'
    text_auth_window = 'Полный доступ к Лабиринту'
    text_phone_number = '8 800 600-95-25'
    text_btn_contakt = 'Соединить с оператором'
    text_books_by_title = 'Уроки французского'
    text_empty_cart = 'Ваша корзина пуста. Почему?'
    base_url = 'https://www.labirint.ru/'
    delivery_and_payment_url = 'https://www.labirint.ru/help/'
    certificate_url = 'https://www.labirint.ru/top/certificates/'
    rating_url = 'https://www.labirint.ru/rating/?id_genre=-1&nrd=1'
    news_url = 'https://www.labirint.ru/novelty/'
    sale_url = 'https://www.labirint.ru/search/?discount=1&available=1&order=actd&way' \
               '=back&paperbooks=1&ebooks=1&otherbooks=1'
    postponed_url = 'https://www.labirint.ru/cabinet/putorder/'
    contakt_url = 'https://www.labirint.ru/contact/'
    support_url = 'https://www.labirint.ru/support/'
    school_url = 'https://www.labirint.ru/school/'
    all_books_url = 'https://www.labirint.ru/books/'
    club_url = 'https://www.labirint.ru/club/'
    office_url = 'https://www.labirint.ru/office/'
    games_url = 'https://www.labirint.ru/games/'
    best_url = 'https://www.labirint.ru/best/'
    souvenir_url = 'https://www.labirint.ru/souvenir/'
    cd_dvd_url = 'https://www.labirint.ru/multimedia/'
    journals_url = 'https://www.labirint.ru/journals/'
    household_url = 'https://www.labirint.ru/household/'
    best_sale_url = 'https://www.labirint.ru/best/sale/'
    now_url = 'https://www.labirint.ru/now/'
    courier_url = 'https://www.labirint.ru/help/?clause=9'
    audio_url = 'https://www.labirint.ru/multimedia/audio'
    help_order_url = 'https://www.labirint.ru/help/?clause=164'
    bonus_url = 'https://www.labirint.ru/help/?clause=82'
    partner_url = 'https://partner.labirint.ru/login'
    books_sale_now = 'https://www.labirint.ru/search/?discount=1&available=1&order=actd&way=back&paperbooks=' \
                     '1&ebooks=1&otherbooks=1'
